spark.master                     spark://10.84.18.85:7077
spark.executor.memory            4g
spark.executor.cores             3
spark.sql.shuffle.partitions     60
spark.pyspark.python             python
spark.pyspark.driver.python      python